# Generated by Django 3.2.6 on 2022-03-15 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campagne', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='color',
        ),
        migrations.RemoveField(
            model_name='player',
            name='id',
        ),
        migrations.AddField(
            model_name='player',
            name='team_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='campagne.team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='bank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
