# Generated by Django 3.2.6 on 2022-03-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagne', '0003_auto_20220315_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
